/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Basic;

import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.Scanner;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emon
 */
public class Basic_Gui extends javax.swing.JFrame {

    String fn, add, country, gendar;
    String dgree = "";
    String gap = " ,";
    JFileChooser fc;
    File dir;
    DefaultTableModel model;
    
    File file = null;

    /**
     * Creates new form Basic_Gui
     */
    public Basic_Gui() {
        initComponents();
        //Table model add
        model = new DefaultTableModel();
        tbl_student.setModel(model);
        
        
        //Table column add
        model.addColumn("Name");
        model.addColumn("Address");
        model.addColumn("Country");
        model.addColumn("Gender");
        model.addColumn("Dgree");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        cmb_country = new javax.swing.JComboBox<>();
        rd_male = new javax.swing.JRadioButton();
        rd_female = new javax.swing.JRadioButton();
        rd_other = new javax.swing.JRadioButton();
        pnl_dgree = new javax.swing.JPanel();
        ssc = new javax.swing.JCheckBox();
        hsc = new javax.swing.JCheckBox();
        bsc = new javax.swing.JCheckBox();
        msc = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_student = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_show = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        btn_displayArea = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Information");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 51))); // NOI18N

        jLabel1.setText("Name      :");

        jLabel2.setText("Address   :");

        jLabel3.setText("Country    :");

        jLabel4.setText("Gender     :");

        jLabel5.setText("Dgree       :");

        cmb_country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- select one --", "Bangladesh", "India", "Thailand", "Nepal", "Australia", "Dubai" }));

        gender.add(rd_male);
        rd_male.setText("Male");
        rd_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_maleActionPerformed(evt);
            }
        });

        gender.add(rd_female);
        rd_female.setText("Female");

        gender.add(rd_other);
        rd_other.setText("Other");

        ssc.setText("SSC");
        ssc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sscActionPerformed(evt);
            }
        });

        hsc.setText("HSC");
        hsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hscActionPerformed(evt);
            }
        });

        bsc.setText("BSC");

        msc.setText("MSC");

        javax.swing.GroupLayout pnl_dgreeLayout = new javax.swing.GroupLayout(pnl_dgree);
        pnl_dgree.setLayout(pnl_dgreeLayout);
        pnl_dgreeLayout.setHorizontalGroup(
            pnl_dgreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dgreeLayout.createSequentialGroup()
                .addComponent(ssc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hsc)
                .addGap(18, 18, 18)
                .addComponent(bsc)
                .addGap(18, 18, 18)
                .addComponent(msc)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        pnl_dgreeLayout.setVerticalGroup(
            pnl_dgreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dgreeLayout.createSequentialGroup()
                .addGroup(pnl_dgreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssc)
                    .addComponent(hsc)
                    .addComponent(bsc)
                    .addComponent(msc))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        tbl_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Country", "Gender", "Dgree"
            }
        ));
        jScrollPane1.setViewportView(tbl_student);

        txt_show.setColumns(20);
        txt_show.setRows(5);
        jScrollPane2.setViewportView(txt_show);

        jLabel7.setText("Name");

        jLabel8.setText("Address");

        jLabel9.setText("Country");

        jLabel10.setText("Gender");

        jLabel11.setText("Dgree");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel8)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel10)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel11)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Students List   :");

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_displayArea.setText("Display Text Area");
        btn_displayArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_displayAreaActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_save)
                .addGap(18, 18, 18)
                .addComponent(btn_displayArea)
                .addGap(33, 33, 33)
                .addComponent(btn_clear)
                .addGap(29, 29, 29)
                .addComponent(btn_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_displayArea)
                    .addComponent(btn_clear)
                    .addComponent(btn_exit))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_address))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmb_country, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd_male)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd_female)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd_other)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(pnl_dgree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rd_male)
                        .addComponent(rd_female)
                        .addComponent(rd_other)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(pnl_dgree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rd_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_maleActionPerformed

    private void sscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sscActionPerformed

    private void hscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hscActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // save data :
        getAllRecord();
        if (txt_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter Your Name ");
            txt_name.requestFocus();
        } else {
            if (cmb_country.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Please Select a Country  ");
                cmb_country.requestFocus();
            } else {
                fc = new JFileChooser(dir);
                //add file filter 
                FileNameExtensionFilter filter;
                filter = new FileNameExtensionFilter("*.txt", new String[]{"txt"});
                fc.addChoosableFileFilter(filter);
                int option = fc.showSaveDialog(this);
                if (option == JFileChooser.APPROVE_OPTION) {
                    dir = fc.getCurrentDirectory();
                    //table add row 
                    model.addRow(new Object[]{fn, add, country, gendar, dgree});
                    file = fc.getSelectedFile();
                    try {
                        writeall();
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                    dgree="";
                }
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_displayAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_displayAreaActionPerformed
        // TODO add your handling code here:
        dispTArea();
    }//GEN-LAST:event_btn_displayAreaActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        
        clearname();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed
    private void getAllRecord() {
        fn = txt_name.getText();
        add = txt_address.getText();
        country = cmb_country.getSelectedItem().toString();
        //radio button gender get data
        if (rd_male.isSelected()) {
            gendar = "Male";
        } else if (rd_female.isSelected()) {
            gendar = "Female";
        } else {
            gendar = "Other";
        }
        //check box dgree get data 
        /* for(int i=0;i<=pnl_dgree.getComponentCount();i++){
           JCheckBox checkbox = (JCheckBox) pnl_dgree.getComponent(i);
           if(checkbox.isSelected()){
               dgree+=checkbox.getText();
               dgree+=gap;
           }
       }
       JOptionPane.showMessageDialog(null, dgree);*/
        for (Component c : pnl_dgree.getComponents()) {
            if (c.getClass().equals(JCheckBox.class)) {
                JCheckBox checkbox = (JCheckBox) c;
                if (checkbox.isSelected()) {
                    dgree += checkbox.getText();
                    dgree += gap;
                }
            }

        }

    }

    private void writeall() throws IOException {
        BufferedWriter buf = null;
        try {
            buf = new BufferedWriter(new FileWriter(file+getextension(),true));
            buf.write(fn+","+add+","+country+","+gendar+","+dgree);
            buf.newLine();
            JOptionPane.showMessageDialog(rootPane, "Save your all information ");
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally{
            if(buf!=null){
                buf.close();
            }
        }

    }

    private String getextension() {
        String ext = "";
        String extension = fc.getFileFilter().getDescription();
        if (extension.equals("*.txt")) {
            ext = ".txt ";
        }
        return ext;
    }
    private void dispTArea(){
        FileInputStream fobj = null;
        fc = new JFileChooser(dir);
        int option = fc.showOpenDialog(this);
        if(option==JFileChooser.APPROVE_OPTION){
            file=fc.getSelectedFile();
            dir=fc.getCurrentDirectory();
            try {
                String str ="";
                fobj = new FileInputStream(file);
                int len = (int)file.length();
                for(int i=0;i<=len;i++){
                    char str2=0;
                    try {
                        str2=(char)fobj.read();
                        if(str2==','){
                            str2='\t';
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    str=str+str2;
                }
                txt_show.setText(str);
            } catch (Exception e) {
                e.printStackTrace();
            }
            finally{
                try {
                    if(fobj!=null){
                        fobj.close();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }
    
    /*private void dispTable(){
    InputStream is=null;
    fc= new JFileChooser(dir);
    int option = fc.showOpenDialog(this);
    if(option==JFileChooser.APPROVE_OPTION){
        file=fc.getSelectedFile();
        dir=fc.getCurrentDirectory();
        try {
            File f = file;
            is = new FileInputStream(f);
            Scanner sc = new Scanner(is);
            String [] arr;
            while (sc.hasNextLine()) {
                String line = sc.nextLine();
                if(line.indexOf(",")>1){
                    arr=line.split(",");
                }else{
                    arr=line.split("\n");
                    
                }
                Object [] data = new Object[arr.length];
                for(int i=0;i<=data.length;i++){
                    data[i]=arr[i];
                }
                model.addRow(data);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally{
            try {
                if(is!=null){
                    is.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    
   
    }*/
    private void clearname(){
        txt_name.setText("");
        txt_address.setText("");
        cmb_country.setSelectedIndex(0);
        txt_show.setText("");
        dgree="";
        gender.clearSelection();
       /* for(int i=0;i<=pnl_dgree.getComponentCount();i++){
            JCheckBox  checkbox = (JCheckBox)pnl_dgree.getComponent(i);
            if(checkbox.isSelected()){
                checkbox.setSelected(false);
            }
        }
        */
       /*for (Component c : pnl_dgree.getComponents()) {
            if (c.getClass().equals(JCheckBox.class)) {
                JCheckBox checkbox = (JCheckBox) c;
                if (checkbox.isSelected()) {
                    checkbox.isSelected();
                }
            }

        }*/
       ssc.setSelected(false);
       hsc.setSelected(false);
       bsc.setSelected(false);
       msc.setSelected(false);
        if(tbl_student.getRowCount()>0){
            for(int i=tbl_student.getRowCount()-1;i<-1;i--){
                model.removeRow(i);
                
            }
        }
        
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Basic_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Basic_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Basic_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Basic_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Basic_Gui().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bsc;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_displayArea;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_country;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JCheckBox hsc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox msc;
    private javax.swing.JPanel pnl_dgree;
    private javax.swing.JRadioButton rd_female;
    private javax.swing.JRadioButton rd_male;
    private javax.swing.JRadioButton rd_other;
    private javax.swing.JCheckBox ssc;
    private javax.swing.JTable tbl_student;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextArea txt_show;
    // End of variables declaration//GEN-END:variables
}
